In [2]:
from tensorflow.keras.preprocessing.text import  one_hot

In [6]:
sent = ['The Glass mof milk', 'The glass OF Juice', 'The Cup Of Tea', 'I am a good boy', 'I am a good developer', 'Understand the meaning of words', 'your videos are good']
sent

['The Glass mof milk',
 'The glass OF Juice',
 'The Cup Of Tea',
 'I am a good boy',
 'I am a good developer',
 'Understand the meaning of words',
 'your videos are good']

In [10]:
# Define the vocabulary size

voc_size = 10000

In [11]:
## One Hot Respresentation

one_hot_rep=[one_hot(words, voc_size) for words in sent]
one_hot_rep

[[5794, 8589, 8537, 6779],
 [5794, 8589, 7466, 4740],
 [5794, 1611, 7466, 4418],
 [5153, 3783, 569, 884, 247],
 [5153, 3783, 569, 884, 9450],
 [9649, 5794, 8765, 7466, 1665],
 [2129, 7866, 8752, 884]]

In [13]:
#word embediing representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [17]:
sent_length = 8
embedding_docs = pad_sequences(one_hot_rep, padding='pre',maxlen=sent_length)
print(embedding_docs)

[[   0    0    0    0 5794 8589 8537 6779]
 [   0    0    0    0 5794 8589 7466 4740]
 [   0    0    0    0 5794 1611 7466 4418]
 [   0    0    0 5153 3783  569  884  247]
 [   0    0    0 5153 3783  569  884 9450]
 [   0    0    0 9649 5794 8765 7466 1665]
 [   0    0    0    0 2129 7866 8752  884]]


In [22]:
#Feature Repesentation

dim = 10

model = Sequential()
model.add(Embedding(voc_size, dim,input_length=sent_length))
model.compile('adam', 'mse')


d:\AGI COURSE BY KRISH NAIK\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [23]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 423ms/step


array([[[-0.03758021, -0.04794154, -0.0231339 ,  0.04186111,
          0.00403378,  0.02417227, -0.00944415, -0.04594388,
         -0.01944058,  0.03798547],
        [-0.03758021, -0.04794154, -0.0231339 ,  0.04186111,
          0.00403378,  0.02417227, -0.00944415, -0.04594388,
         -0.01944058,  0.03798547],
        [-0.03758021, -0.04794154, -0.0231339 ,  0.04186111,
          0.00403378,  0.02417227, -0.00944415, -0.04594388,
         -0.01944058,  0.03798547],
        [-0.03758021, -0.04794154, -0.0231339 ,  0.04186111,
          0.00403378,  0.02417227, -0.00944415, -0.04594388,
         -0.01944058,  0.03798547],
        [-0.02779733, -0.03056905,  0.04405298,  0.00367439,
         -0.04178566, -0.034608  , -0.04243479,  0.02094224,
          0.00390835,  0.04204513],
        [ 0.00012063,  0.04984855,  0.0232586 ,  0.01350062,
         -0.03916102,  0.04410627,  0.03904324, -0.02486387,
         -0.00989195,  0.0011156 ],
        [ 0.02447982,  0.01241336,  0.02996149, -0.0

In [26]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step


array([[[-0.03758021, -0.04794154, -0.0231339 ,  0.04186111,
          0.00403378,  0.02417227, -0.00944415, -0.04594388,
         -0.01944058,  0.03798547],
        [-0.03758021, -0.04794154, -0.0231339 ,  0.04186111,
          0.00403378,  0.02417227, -0.00944415, -0.04594388,
         -0.01944058,  0.03798547],
        [-0.03758021, -0.04794154, -0.0231339 ,  0.04186111,
          0.00403378,  0.02417227, -0.00944415, -0.04594388,
         -0.01944058,  0.03798547],
        [-0.03758021, -0.04794154, -0.0231339 ,  0.04186111,
          0.00403378,  0.02417227, -0.00944415, -0.04594388,
         -0.01944058,  0.03798547],
        [-0.02779733, -0.03056905,  0.04405298,  0.00367439,
         -0.04178566, -0.034608  , -0.04243479,  0.02094224,
          0.00390835,  0.04204513],
        [ 0.00012063,  0.04984855,  0.0232586 ,  0.01350062,
         -0.03916102,  0.04410627,  0.03904324, -0.02486387,
         -0.00989195,  0.0011156 ],
        [ 0.02447982,  0.01241336,  0.02996149, -0.0